# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-15 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorAppII', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='These are the notes for the books'),
            preserve_default=False,
        ),
    ]
